# -*- coding: utf-8 -*-
"""linear_regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11w6_2D2NDCCNJMsiMJyg763ZhMtTtiBW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/new_insurance_data (1).csv")
df

df.info()

df.isnull().sum()

df.dropna(inplace=True)
df.isnull().sum()

df.duplicated().sum()

for col in df.columns:
  if(df[col].dtype!='object'):
    sns.boxplot(df[col])
    plt.xlabel(col)
    plt.show()

out_list=['bmi','past_consultations','Hospital_expenditure','Anual_Salary','charges']
for col in out_list:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)

  iqr=Q3-Q1

  lb=Q1-1.5*(iqr)
  ub=Q3+1.5*(iqr)

  df=df[(df[col]>=lb) & (df[col]<=ub)]

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for col in df.columns:
  if(df[col].dtype=='object'):
    df[col]=le.fit_transform(df[col])

df

x=df.drop('charges',axis=1)
y=df['charges']
x

y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x_train,y_train)

model_answers=model.predict(x_test)
model_answers

from sklearn.metrics import r2_score

r2_score(model_answers,y_test)*100

sns.regplot(x=model_answers,y=y_test)
plt.xlabel('predicted_values')